"""
Seed resource dataset. Each entry maps to one or more skills it teaches
and (optionally) skills it requires as prerequisites. URLs point to real,
well-known official documentation or free learning platforms - no fake
URLs are used, per project requirements.
"""

# Each: title, description, provider, url, resource_type, difficulty,
# estimated_hours, skills (taught), prerequisites (skill names required)
RESOURCES = [
    # ---------------- Tools ----------------
    dict(title="Git & GitHub Crash Course", description="Learn version control fundamentals: commits, branches, merges, and collaborating on GitHub.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/news/git-and-github-for-beginners/",
         resource_type="Course", difficulty="Beginner", estimated_hours=4, skills=["Git"], prerequisites=[]),
    dict(title="Pro Git Book", description="The definitive free reference book covering Git in depth, from basics to internals.",
         provider="Git", url="https://git-scm.com/book/en/v2",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=6, skills=["Git"], prerequisites=[]),
    dict(title="Linux Journey", description="Interactive, beginner-friendly path through the Linux command line, file system, and permissions.",
         provider="Linux Journey", url="https://linuxjourney.com/",
         resource_type="Course", difficulty="Beginner", estimated_hours=8, skills=["Linux Fundamentals"], prerequisites=[]),

    # ---------------- Frontend ----------------
    dict(title="Responsive Web Design Certification", description="Hands-on curriculum covering HTML structure and CSS layout, flexbox, and grid.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/learn/2022/responsive-web-design/",
         resource_type="Course", difficulty="Beginner", estimated_hours=20, skills=["HTML & CSS"], prerequisites=[]),
    dict(title="MDN HTML Reference", description="Official, comprehensive reference and guides for HTML elements and semantics.",
         provider="MDN Web Docs", url="https://developer.mozilla.org/en-US/docs/Web/HTML",
         resource_type="Documentation", difficulty="Beginner", estimated_hours=3, skills=["HTML & CSS"], prerequisites=[]),
    dict(title="JavaScript Algorithms and Data Structures", description="Core JavaScript syntax, ES6+, and algorithmic thinking through practice problems.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/",
         resource_type="Course", difficulty="Beginner", estimated_hours=25, skills=["JavaScript"], prerequisites=["HTML & CSS"]),
    dict(title="MDN JavaScript Guide", description="Official in-depth guide to JavaScript language fundamentals and modern features.",
         provider="MDN Web Docs", url="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=8, skills=["JavaScript"], prerequisites=["HTML & CSS"]),
    dict(title="TypeScript Handbook", description="Official handbook covering TypeScript's type system from the basics to advanced generics.",
         provider="TypeScript", url="https://www.typescriptlang.org/docs/handbook/intro.html",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=6, skills=["TypeScript"], prerequisites=["JavaScript"]),
    dict(title="React Official Docs - Learn React", description="Official interactive tutorial covering components, state, props, and hooks.",
         provider="React", url="https://react.dev/learn",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=12, skills=["React"], prerequisites=["JavaScript"]),
    dict(title="Build a Personal Portfolio with React", description="Project: build and deploy a multi-page portfolio site using React components and routing.",
         provider="React", url="https://react.dev/learn/tutorial-tic-tac-toe",
         resource_type="Project", difficulty="Intermediate", estimated_hours=10, skills=["React"], prerequisites=["JavaScript"]),
    dict(title="Web.dev Accessibility Course", description="Practical guide to building accessible web experiences: semantics, ARIA, keyboard navigation.",
         provider="web.dev (Google)", url="https://web.dev/learn/accessibility/",
         resource_type="Course", difficulty="Intermediate", estimated_hours=6, skills=["Web Accessibility"], prerequisites=["HTML & CSS"]),

    # ---------------- Programming / Backend ----------------
    dict(title="Python for Everybody", description="Beginner-friendly introduction to Python programming, covering variables, control flow, and functions.",
         provider="Coursera (University of Michigan)", url="https://www.coursera.org/specializations/python",
         resource_type="Course", difficulty="Beginner", estimated_hours=30, skills=["Python"], prerequisites=[]),
    dict(title="Official Python Tutorial", description="The official Python.org tutorial covering the language from the ground up.",
         provider="Python.org", url="https://docs.python.org/3/tutorial/",
         resource_type="Documentation", difficulty="Beginner", estimated_hours=10, skills=["Python"], prerequisites=[]),
    dict(title="SQL for Data Analysis", description="Learn SQL fundamentals: SELECT, JOIN, GROUP BY, and subqueries through hands-on exercises.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/learn/relational-database/",
         resource_type="Course", difficulty="Beginner", estimated_hours=12, skills=["SQL"], prerequisites=[]),
    dict(title="PostgreSQL Official Tutorial", description="Official PostgreSQL tutorial covering queries, joins, and database design.",
         provider="PostgreSQL", url="https://www.postgresql.org/docs/current/tutorial.html",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=8, skills=["SQL"], prerequisites=[]),
    dict(title="HTTP & REST APIs Explained", description="MDN's guide to how HTTP works and REST API design conventions.",
         provider="MDN Web Docs", url="https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview",
         resource_type="Article", difficulty="Beginner", estimated_hours=3, skills=["REST APIs"], prerequisites=["Python"]),
    dict(title="Build a REST API Project", description="Project: design and implement a CRUD REST API with proper status codes and validation.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/news/build-a-rest-api-with-python/",
         resource_type="Project", difficulty="Intermediate", estimated_hours=10, skills=["REST APIs"], prerequisites=["Python"]),
    dict(title="FastAPI Official Tutorial", description="Official step-by-step tutorial for building typed, async APIs with FastAPI.",
         provider="FastAPI", url="https://fastapi.tiangolo.com/tutorial/",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=10, skills=["FastAPI"], prerequisites=["REST APIs"]),
    dict(title="Django Official Tutorial", description="Official 'polls app' tutorial covering models, views, templates, and the admin site.",
         provider="Django", url="https://docs.djangoproject.com/en/stable/intro/tutorial01/",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=12, skills=["Django"], prerequisites=["REST APIs"]),
    dict(title="Grokking System Design Fundamentals", description="Free video series covering scalability, load balancing, caching, and system design interviews.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/news/systems-design-for-interviews/",
         resource_type="Course", difficulty="Advanced", estimated_hours=15, skills=["System Design"], prerequisites=["REST APIs"]),

    # ---------------- DevOps ----------------
    dict(title="Docker Get Started Guide", description="Official Docker guide to containerizing an application from scratch.",
         provider="Docker", url="https://docs.docker.com/get-started/",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=6, skills=["Docker"], prerequisites=["Linux Fundamentals"]),
    dict(title="Dockerize a Full-Stack App Project", description="Project: containerize a multi-service app with Docker Compose.",
         provider="Docker", url="https://docs.docker.com/compose/gettingstarted/",
         resource_type="Project", difficulty="Intermediate", estimated_hours=8, skills=["Docker"], prerequisites=["Linux Fundamentals"]),
    dict(title="Kubernetes Basics Tutorial", description="Official interactive tutorial covering pods, deployments, and services.",
         provider="Kubernetes", url="https://kubernetes.io/docs/tutorials/kubernetes-basics/",
         resource_type="Documentation", difficulty="Advanced", estimated_hours=12, skills=["Kubernetes"], prerequisites=["Docker"]),
    dict(title="GitHub Actions CI/CD Guide", description="Official guide to automating build, test, and deploy pipelines with GitHub Actions.",
         provider="GitHub", url="https://docs.github.com/en/actions/learn-github-actions",
         resource_type="Documentation", difficulty="Intermediate", estimated_hours=6, skills=["CI/CD"], prerequisites=["Git"]),
    dict(title="AWS Cloud Practitioner Essentials", description="Free official course covering core AWS services: EC2, S3, IAM, and pricing.",
         provider="AWS Skill Builder", url="https://skillbuilder.aws/",
         resource_type="Course", difficulty="Intermediate", estimated_hours=10, skills=["AWS"], prerequisites=["Docker"]),
    dict(title="Prometheus & Grafana Monitoring Guide", description="Official docs for setting up metrics collection and dashboards for production systems.",
         provider="Prometheus / Grafana", url="https://prometheus.io/docs/introduction/overview/",
         resource_type="Documentation", difficulty="Advanced", estimated_hours=8, skills=["Monitoring & Observability"], prerequisites=["Kubernetes"]),

    # ---------------- Data Science ----------------
    dict(title="NumPy Quickstart Tutorial", description="Official guide to arrays, broadcasting, and vectorized operations in NumPy.",
         provider="NumPy", url="https://numpy.org/doc/stable/user/quickstart.html",
         resource_type="Documentation", difficulty="Beginner", estimated_hours=4, skills=["NumPy"], prerequisites=["Python"]),
    dict(title="pandas Getting Started Guide", description="Official tutorials for loading, cleaning, and analyzing tabular data with pandas.",
         provider="pandas", url="https://pandas.pydata.org/docs/getting_started/index.html",
         resource_type="Documentation", difficulty="Beginner", estimated_hours=6, skills=["Pandas"], prerequisites=["NumPy"]),
    dict(title="Statistics and Probability", description="Free course covering descriptive statistics, distributions, and hypothesis testing.",
         provider="Khan Academy", url="https://www.khanacademy.org/math/statistics-probability",
         resource_type="Course", difficulty="Intermediate", estimated_hours=20, skills=["Statistics"], prerequisites=["Pandas"]),
    dict(title="Probability Fundamentals", description="Free course covering probability rules, random variables, and distributions.",
         provider="Khan Academy", url="https://www.khanacademy.org/math/statistics-probability/probability-library",
         resource_type="Course", difficulty="Intermediate", estimated_hours=12, skills=["Probability"], prerequisites=["Statistics"]),
    dict(title="Essence of Linear Algebra", description="Visual, intuition-first video series covering vectors, matrices, and transformations.",
         provider="3Blue1Brown (YouTube)", url="https://www.3blue1brown.com/topics/linear-algebra",
         resource_type="Video", difficulty="Intermediate", estimated_hours=6, skills=["Linear Algebra"], prerequisites=["Statistics"]),
    dict(title="Data Visualization with Matplotlib & Seaborn", description="Official guides for building static and statistical charts in Python.",
         provider="Matplotlib", url="https://matplotlib.org/stable/tutorials/index.html",
         resource_type="Documentation", difficulty="Beginner", estimated_hours=6, skills=["Data Visualization"], prerequisites=["Pandas"]),
    dict(title="Exploratory Data Analysis Project", description="Project: clean, visualize, and summarize insights from a real-world dataset.",
         provider="Kaggle", url="https://www.kaggle.com/learn/data-visualization",
         resource_type="Project", difficulty="Beginner", estimated_hours=8, skills=["Data Visualization"], prerequisites=["Pandas"]),

    # ---------------- AI / ML ----------------
    dict(title="Machine Learning Crash Course", description="Google's free, practical introduction to ML concepts with TensorFlow exercises.",
         provider="Google Developers", url="https://developers.google.com/machine-learning/crash-course",
         resource_type="Course", difficulty="Intermediate", estimated_hours=15, skills=["Machine Learning"], prerequisites=["Probability", "Linear Algebra", "Pandas"]),
    dict(title="Machine Learning Specialization", description="Andrew Ng's widely-used course covering supervised and unsupervised learning fundamentals.",
         provider="Coursera (DeepLearning.AI)", url="https://www.coursera.org/specializations/machine-learning-introduction",
         resource_type="Course", difficulty="Intermediate", estimated_hours=40, skills=["Machine Learning"], prerequisites=["Probability", "Linear Algebra", "Pandas"]),
    dict(title="Build a Machine Learning Project", description="Project: train, evaluate, and deploy a scikit-learn model end to end on a real dataset.",
         provider="scikit-learn", url="https://scikit-learn.org/stable/tutorial/index.html",
         resource_type="Project", difficulty="Intermediate", estimated_hours=12, skills=["Machine Learning"], prerequisites=["Probability", "Linear Algebra", "Pandas"]),
    dict(title="Deep Learning Specialization", description="DeepLearning.AI's foundational specialization covering neural networks, CNNs, and RNNs.",
         provider="Coursera (DeepLearning.AI)", url="https://www.coursera.org/specializations/deep-learning",
         resource_type="Course", difficulty="Advanced", estimated_hours=50, skills=["Deep Learning"], prerequisites=["Machine Learning"]),
    dict(title="Practical Deep Learning for Coders", description="Free, top-down, project-based deep learning course using PyTorch.",
         provider="fast.ai", url="https://course.fast.ai/",
         resource_type="Course", difficulty="Advanced", estimated_hours=35, skills=["Deep Learning"], prerequisites=["Machine Learning"]),
    dict(title="TensorFlow Official Tutorials", description="Official beginner-to-advanced tutorials for building models with TensorFlow/Keras.",
         provider="TensorFlow", url="https://www.tensorflow.org/tutorials",
         resource_type="Documentation", difficulty="Advanced", estimated_hours=15, skills=["TensorFlow"], prerequisites=["Deep Learning"]),
    dict(title="PyTorch Official Tutorials", description="Official 60-minute blitz and deeper tutorials for building models with PyTorch.",
         provider="PyTorch", url="https://pytorch.org/tutorials/",
         resource_type="Documentation", difficulty="Advanced", estimated_hours=15, skills=["PyTorch"], prerequisites=["Deep Learning"]),
    dict(title="Hugging Face NLP Course", description="Free official course covering transformers, tokenization, and fine-tuning for NLP tasks.",
         provider="Hugging Face", url="https://huggingface.co/learn/nlp-course",
         resource_type="Course", difficulty="Advanced", estimated_hours=20, skills=["NLP"], prerequisites=["Deep Learning"]),
    dict(title="Building LLM Applications", description="Short course covering prompt engineering, RAG, and building apps on top of LLMs.",
         provider="DeepLearning.AI", url="https://www.deeplearning.ai/short-courses/",
         resource_type="Course", difficulty="Advanced", estimated_hours=10, skills=["LLM Engineering"], prerequisites=["NLP", "PyTorch"]),
    dict(title="Build a RAG-based Chat Assistant", description="Project: build a retrieval-augmented generation app using embeddings and an LLM API.",
         provider="Hugging Face", url="https://huggingface.co/learn/cookbook",
         resource_type="Project", difficulty="Advanced", estimated_hours=15, skills=["LLM Engineering"], prerequisites=["NLP", "PyTorch"]),
    dict(title="Made With ML - MLOps Course", description="Free course covering the full ML lifecycle: testing, CI/CD, deployment, and monitoring for ML.",
         provider="Made With ML", url="https://madewithml.com/",
         resource_type="Course", difficulty="Advanced", estimated_hours=20, skills=["MLOps"], prerequisites=["Machine Learning", "Docker"]),
    dict(title="Google Cloud MLOps Guide", description="Official guide to continuous training, model versioning, and MLOps maturity levels.",
         provider="Google Cloud", url="https://cloud.google.com/architecture/mlops-continuous-delivery-and-automation-pipelines-in-machine-learning",
         resource_type="Documentation", difficulty="Advanced", estimated_hours=8, skills=["MLOps"], prerequisites=["Machine Learning", "Docker"]),

    # ---------------- Assessments as resources (lightweight, optional extra) ----------------
    dict(title="Python Fundamentals Practice Set", description="Practice problems reinforcing Python syntax, functions, and data structures.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/learn/scientific-computing-with-python/",
         resource_type="Article", difficulty="Beginner", estimated_hours=5, skills=["Python"], prerequisites=[]),
    dict(title="SQL Practice Exercises", description="Hands-on SQL query exercises against sample databases.",
         provider="PostgreSQL Exercises", url="https://pgexercises.com/",
         resource_type="Article", difficulty="Beginner", estimated_hours=4, skills=["SQL"], prerequisites=[]),
    dict(title="freeCodeCamp Full Stack Certification Path", description="Full multi-module curriculum covering front-end libraries, APIs, and databases.",
         provider="freeCodeCamp", url="https://www.freecodecamp.org/learn/",
         resource_type="Course", difficulty="Intermediate", estimated_hours=40, skills=["JavaScript", "REST APIs"], prerequisites=["HTML & CSS"]),
    dict(title="Kaggle Python Micro-Course", description="Short, hands-on micro-course covering Python essentials for data work.",
         provider="Kaggle", url="https://www.kaggle.com/learn/python",
         resource_type="Course", difficulty="Beginner", estimated_hours=5, skills=["Python"], prerequisites=[]),
    dict(title="Kaggle Intro to Machine Learning", description="Short, practical micro-course covering the core ML workflow with real datasets.",
         provider="Kaggle", url="https://www.kaggle.com/learn/intro-to-machine-learning",
         resource_type="Course", difficulty="Intermediate", estimated_hours=6, skills=["Machine Learning"], prerequisites=["Probability", "Linear Algebra", "Pandas"]),
]
